version: '3.2'

services:

  proxy:
    image: caspiorlie50/proxy-custom
    ports:
      - 80:80
    networks:
      - ext_net
      - proxy_net
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
       test: curl -f http://localhost/ || exit 0
       interval: 1s
       retries: 5
    volumes:
      - nginx-dir:/etc/nginx/conf.d 

  web:
    image: caspiorlie50/web-custom
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
    healthcheck:
      test: curl -f http://localhost/ || exit 0
      interval: 1s
      retries: 5
    volumes:
      - php-fileweb:/var/www/html

  pma:
    image: caspiorlie50/pma-custom
    networks:
      - proxy_net
      - int_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
    healthcheck:
      test: curl -f http://localhost/ || exit 0
      interval: 1s
      retries: 5
    volumes:
      - phpmyadmin-data:/var/lib/docker/volumes/phpmyadmin-data
    environment:  
      - PMA_HOST=mysql
      - PMA_USER_FILE=/run/secrets/psql_user
      - PMA_PASSWORD_FILE=/run/secrets/psql_pass

  mysql:
    image: caspiorlie50/mysql-custom
    networks:
      - int_net
    secrets:
      - psql_user
      - psql_pass
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
      interval: 1s
      timeout: 3s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=YES 
      - MYSQL_DATABASE=dbkuasai
      - MYSQL_USER_FILE=/run/secrets/psql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/psql_pass

volumes:
  php-fileweb:
  nginx-dir:
  phpmyadmin-data:
  mysql-data:

networks:
  ext_net:
    driver: overlay
  proxy_net:
    driver: overlay
  int_net:
    driver: overlay

secrets:
  psql_user:
    file: ./psql_user.txt
  psql_pass:
    file: ./psql_pass.txt